CREATE TABLE cart_items(
    id bigint generated by default as identity,
    cart_id bigint not null,
    product_id bigint not null,
    quantity  varchar(254) not null default 'NA',
    primary key(id)
);